# Generated by Django 5.0.14 on 2025-09-18 17:29

import apps.calendars.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "holiday_name",
                    models.CharField(
                        choices=[
                            ("new_years", "New Year's Day"),
                            ("easter", "Easter"),
                            ("mothers_day", "Mother's Day"),
                            ("fathers_day", "Father's Day"),
                            ("memorial_day", "Memorial Day"),
                            ("independence_day", "Independence Day"),
                            ("labor_day", "Labor Day"),
                            ("thanksgiving", "Thanksgiving"),
                            ("christmas", "Christmas"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "include_image",
                    models.BooleanField(
                        default=False, help_text="Include an image for this holiday"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image for this holiday",
                        null=True,
                        upload_to=apps.calendars.models.holiday_image_upload_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="calendars.calendar",
                    ),
                ),
            ],
            options={
                "ordering": ["calendar", "holiday_name"],
                "unique_together": {("calendar", "holiday_name")},
            },
        ),
    ]
