# Generated by Django 5.0.14 on 2025-09-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0005_calendarevent_combined_events_calendaryear_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmaster",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Default image for this event (will be copied to calendar events)",
                null=True,
                upload_to="master_events/%Y/%m/",
            ),
        ),
    ]
