# Generated by Django 5.0.14 on 2025-09-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0006_eventmaster_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="usereventpreferences",
            name="show_age_numbers",
            field=models.BooleanField(
                default=True,
                help_text="Show age numbers for birthdays and anniversary years (e.g., '25th Birthday' vs 'Birthday')",
            ),
        ),
    ]
