# Generated by Django 5.0.14 on 2025-09-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0007_usereventpreferences_show_age_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="is_publicly_shared",
            field=models.BooleanField(
                default=False, help_text="Whether this calendar is publicly shareable"
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="public_share_token",
            field=models.CharField(
                blank=True,
                help_text="Token for public sharing - allows viewing without login",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
