# Generated by Django 5.0.14 on 2025-09-20 13:12

import apps.calendars.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0008_calendar_is_publicly_shared_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarHeaderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (0, "Cover/Title Page"),
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        help_text="Month (0=Cover page, 1=January, etc.)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Header image for this month",
                        upload_to=apps.calendars.models.calendar_header_upload_path,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title/caption for this header",
                        max_length=255,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="header_images",
                        to="calendars.calendar",
                    ),
                ),
            ],
            options={
                "ordering": ["month"],
                "unique_together": {("calendar", "month")},
            },
        ),
    ]
