# Generated by Django 5.0.14 on 2025-09-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0009_calendarheaderimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarheaderimage",
            name="month",
            field=models.IntegerField(
                choices=[
                    (0, "Cover/Title Page"),
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                    (13, "Back Cover"),
                ],
                help_text="Month (0=Cover page, 1=January, etc.)",
            ),
        ),
    ]
