# Generated by Django 5.0.14 on 2025-09-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0010_alter_calendarheaderimage_month"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="generatedcalendar",
            unique_together={("calendar", "generation_type")},
        ),
    ]
