# Generated by Django 5.0.14 on 2025-09-20 22:35

import apps.calendars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0011_alter_generatedcalendar_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="full_image",
            field=models.ImageField(
                blank=True,
                help_text="Full-sized original image for digital calendar viewing",
                null=True,
                upload_to=apps.calendars.models.calendar_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="image",
            field=models.ImageField(
                help_text="Cropped image file for this event (used in PDF generation)",
                upload_to=apps.calendars.models.calendar_image_upload_path,
            ),
        ),
    ]
