# Generated by Django 5.0.14 on 2025-09-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0012_calendarevent_full_image_alter_calendarevent_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendarevent",
            options={"ordering": ["calendar", "month", "day", "created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="calendarevent",
            unique_together=set(),
        ),
    ]
