# Generated by Django 5.0.14 on 2025-09-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0013_alter_calendarevent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usereventpreferences",
            name="image_combination_layout",
            field=models.CharField(
                choices=[
                    ("auto", "Automatic - System chooses best layout"),
                    ("side_by_side", "Side by side - Images placed horizontally"),
                    ("top_bottom", "Top/Bottom - Images stacked vertically"),
                    ("grid", "Grid - Always use 2x2 grid layout"),
                ],
                default="auto",
                help_text="Default layout for combining multiple event images",
                max_length=15,
            ),
        ),
    ]
