# Generated by Django 5.0.14 on 2025-09-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0014_usereventpreferences_image_combination_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmaster",
            name="full_image",
            field=models.ImageField(
                blank=True,
                help_text="Full-sized original image for high-resolution viewing",
                null=True,
                upload_to="master_events/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="eventmaster",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Cropped image for this event (used in PDF generation)",
                null=True,
                upload_to="master_events/%Y/%m/",
            ),
        ),
    ]
