# Generated by Django 5.0.14 on 2026-04-03 19:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0015_eventmaster_full_image_alter_eventmaster_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="pdf_override_day_number_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("small", "Small - 8-9pt"),
                    ("medium", "Medium - 9-10pt (default)"),
                    ("large", "Large - 10-11pt"),
                ],
                help_text="Override user's default day number size for this calendar",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="pdf_override_event_text_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("small", "Small - 8-9pt"),
                    ("medium", "Medium - 9-10pt (default)"),
                    ("large", "Large - 10-11pt"),
                ],
                help_text="Override user's default event text size for this calendar",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="pdf_override_image_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("small", "Small - Compact layout"),
                    ("medium", "Medium - Balanced (default)"),
                    ("large", "Large - Maximum size"),
                ],
                help_text="Override user's default image size for this calendar",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="pdf_override_layout_compactness",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compact", "Compact - Minimal spacing"),
                    ("normal", "Normal - Balanced spacing (default)"),
                    ("spacious", "Spacious - Maximum spacing"),
                ],
                help_text="Override user's default layout compactness",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="pdf_override_text_bg_color",
            field=models.CharField(
                blank=True,
                choices=[("white", "White background"), ("black", "Black background")],
                help_text="Override user's default text background color",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="pdf_override_text_position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("top_overlay", "Top of image"),
                    ("bottom_overlay", "Bottom of image (default)"),
                    ("below_image", "Below image"),
                ],
                help_text="Override user's default text position",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="pdf_override_text_transparency",
            field=models.IntegerField(
                blank=True,
                help_text="Override user's default text transparency (0-100%)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.CreateModel(
            name="UserPDFSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_size",
                    models.CharField(
                        choices=[
                            ("small", "Small - Compact layout"),
                            ("medium", "Medium - Balanced (default)"),
                            ("large", "Large - Maximum size"),
                        ],
                        default="medium",
                        help_text="Size of event images in PDF",
                        max_length=10,
                    ),
                ),
                (
                    "event_text_size",
                    models.CharField(
                        choices=[
                            ("small", "Small - 8-9pt"),
                            ("medium", "Medium - 9-10pt (default)"),
                            ("large", "Large - 10-11pt"),
                        ],
                        default="medium",
                        help_text="Font size for event names",
                        max_length=10,
                    ),
                ),
                (
                    "day_number_size",
                    models.CharField(
                        choices=[
                            ("small", "Small - 8-9pt"),
                            ("medium", "Medium - 9-10pt (default)"),
                            ("large", "Large - 10-11pt"),
                        ],
                        default="medium",
                        help_text="Font size for day numbers",
                        max_length=10,
                    ),
                ),
                (
                    "text_transparency",
                    models.IntegerField(
                        default=50,
                        help_text="0 = fully transparent, 100 = solid",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "text_bg_color",
                    models.CharField(
                        choices=[
                            ("white", "White background"),
                            ("black", "Black background"),
                        ],
                        default="white",
                        help_text="Background color for text boxes",
                        max_length=10,
                    ),
                ),
                (
                    "text_position",
                    models.CharField(
                        choices=[
                            ("top_overlay", "Top of image"),
                            ("bottom_overlay", "Bottom of image (default)"),
                            ("below_image", "Below image"),
                        ],
                        default="bottom_overlay",
                        help_text="Where to position event text",
                        max_length=15,
                    ),
                ),
                (
                    "layout_compactness",
                    models.CharField(
                        choices=[
                            ("compact", "Compact - Minimal spacing"),
                            ("normal", "Normal - Balanced spacing (default)"),
                            ("spacious", "Spacious - Maximum spacing"),
                        ],
                        default="normal",
                        help_text="Spacing around text boxes",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
