# Generated by Django 5.0.14 on 2026-04-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0016_calendar_pdf_override_day_number_size_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="generatedcalendar",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="generatedcalendar",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Optional custom name for this PDF (e.g., 'Final Version', 'For Grandma')",
                max_length=100,
            ),
        ),
    ]
